### PR TITLE
Link over to dartlang package

### PR DESCRIPTION
**Pull request by sethladd**
It's the new new one :)

### CODE REVIEW

**Comment by steelbrain** [comment]
How about your list both of them? :)

**Comment by sethladd** [comment]
If dart-tools is still actively maintained, then we should.

@radicaled what do you think?

**Comment by radicaled** [comment]
I haven't officially deprecated `dart-tools`, but `dartlang` offers a much better experience at the moment, so preferring it would be best.

**Comment by steelbrain** [comment]
@radicaled have you guys discussed about merging the projects? :)

**Comment by radicaled** [comment]
@steelbrain I'm technically a contributor to both projects!

But they're written in different languages, and `dart-tools` is a bit more simpler. Most people will want `dartlang` since they're refugees from an all-in-one IDE experience.

**Comment by steelbrain** [comment]
@radicaled in any case, You should try to reduce the complexity of the complex one, Otherwise it can be a great pain to maintain two identical projects simultanously

**Pull request merged**
